/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    login: "tetondan",
    id: 8883343,
    node_id: "MDQ6VXNlcjg4ODMzNDM=",
    avatar_url: "https://avatars.githubusercontent.com/u/8883343?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/tetondan",
    html_url: "https://github.com/tetondan",
    followers_url: "https://api.github.com/users/tetondan/followers",
    following_url: "https://api.github.com/users/tetondan/following{/other_user}",
    gists_url: "https://api.github.com/users/tetondan/gists{/gist_id}",
    starred_url: "https://api.github.com/users/tetondan/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/tetondan/subscriptions",
    organizations_url: "https://api.github.com/users/tetondan/orgs",
    repos_url: "https://api.github.com/users/tetondan/repos",
    events_url: "https://api.github.com/users/tetondan/events{/privacy}",
    received_events_url: "https://api.github.com/users/tetondan/received_events",
    type: "User",
    site_admin: false,
    name: "Daniel Frehner",
    company: "@replit ",
    blog: "http://www.danielfrehner.com",
    location: "Jackson Hole, Wy",
    email: null,
    hireable: null,
    bio: "Engineer @ Repl.it\r\n",
    twitter_username: null,
    public_repos: 64,
    public_gists: 3,
    followers: 176,
    following: 8,
    created_at: "2014-09-23T17:47:56Z",
    updated_at: "2021-07-29T00:02:27Z",
  }, 
  {
    login: "rkshockey",
    id: 84862108,
    node_id: "MDQ6VXNlcjg0ODYyMTA4",
    avatar_url: "https://avatars.githubusercontent.com/u/84862108?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rkshockey",
    html_url: "https://github.com/rkshockey",
    followers_url: "https://api.github.com/users/rkshockey/followers",
    following_url: "https://api.github.com/users/rkshockey/following{/other_user}",
    gists_url: "https://api.github.com/users/rkshockey/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rkshockey/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rkshockey/subscriptions",
    organizations_url: "https://api.github.com/users/rkshockey/orgs",
    repos_url: "https://api.github.com/users/rkshockey/repos",
    events_url: "https://api.github.com/users/rkshockey/events{/privacy}",
    received_events_url: "https://api.github.com/users/rkshockey/received_events",
    type: "User",
    site_admin: false,
    name: "Romy Shockey",
    company: null,
    blog: "",
    location: "York, PA",
    email: null,
    hireable: true,
    bio: "I'm a student at Lambda School who loves reading and hikes.",
    twitter_username: null,
    public_repos: 35,
    public_gists: 0,
    followers: 10,
    following: 12,
    created_at: "2021-05-26T15:24:45Z",
    updated_at: "2021-08-03T19:52:02Z"
  },
  {
    login: "Andrewschaer",
    id: 24277559,
    node_id: "MDQ6VXNlcjI0Mjc3NTU5",
    avatar_url: "https://avatars.githubusercontent.com/u/24277559?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Andrewschaer",
    html_url: "https://github.com/Andrewschaer",
    followers_url: "https://api.github.com/users/Andrewschaer/followers",
    following_url: "https://api.github.com/users/Andrewschaer/following{/other_user}",
    gists_url: "https://api.github.com/users/Andrewschaer/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Andrewschaer/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Andrewschaer/subscriptions",
    organizations_url: "https://api.github.com/users/Andrewschaer/orgs",
    repos_url: "https://api.github.com/users/Andrewschaer/repos",
    events_url: "https://api.github.com/users/Andrewschaer/events{/privacy}",
    received_events_url: "https://api.github.com/users/Andrewschaer/received_events",
    type: "User",
    site_admin: false,
    name: 'Andrew Schaer',
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 36,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: "2016-11-30T18:10:01Z",
    updated_at: "2021-07-26T18:27:30Z"
  },
  {
    login: "katherineyevsukov",
    id: 58489217,
    node_id: "MDQ6VXNlcjU4NDg5MjE3",
    avatar_url: "https://avatars.githubusercontent.com/u/58489217?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/katherineyevsukov",
    html_url: "https://github.com/katherineyevsukov",
    followers_url: "https://api.github.com/users/katherineyevsukov/followers",
    following_url: "https://api.github.com/users/katherineyevsukov/following{/other_user}",
    gists_url: "https://api.github.com/users/katherineyevsukov/gists{/gist_id}",
    starred_url: "https://api.github.com/users/katherineyevsukov/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/katherineyevsukov/subscriptions",
    organizations_url: "https://api.github.com/users/katherineyevsukov/orgs",
    repos_url: "https://api.github.com/users/katherineyevsukov/repos",
    events_url: "https://api.github.com/users/katherineyevsukov/events{/privacy}",
    received_events_url: "https://api.github.com/users/katherineyevsukov/received_events",
    type: "User",
    site_admin: false,
    name: "Katherine Yevsukov",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 36,
    public_gists: 0,
    followers: 5,
    following: 4,
    created_at: "2019-12-03T20:49:24Z",
    updated_at: "2021-08-03T20:31:35Z"
  },
  {
    login: "Jie-chelchel",
    id: 84593843,
    node_id: "MDQ6VXNlcjg0NTkzODQz",
    avatar_url: "https://avatars.githubusercontent.com/u/84593843?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Jie-chelchel",
    html_url: "https://github.com/Jie-chelchel",
    followers_url: "https://api.github.com/users/Jie-chelchel/followers",
    following_url: "https://api.github.com/users/Jie-chelchel/following{/other_user}",
    gists_url: "https://api.github.com/users/Jie-chelchel/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Jie-chelchel/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Jie-chelchel/subscriptions",
    organizations_url: "https://api.github.com/users/Jie-chelchel/orgs",
    repos_url: "https://api.github.com/users/Jie-chelchel/repos",
    events_url: "https://api.github.com/users/Jie-chelchel/events{/privacy}",
    received_events_url: "https://api.github.com/users/Jie-chelchel/received_events",
    type: "User",
    site_admin: false,
    name: "Jie Zhang",
    company: null,
    blog: "",
    location: "Longmont CO",
    email: null,
    hireable: null,
    bio: "I enjoy making things that make people happy.",
    twitter_username: null,
    public_repos: 44,
    public_gists: 0,
    followers: 15,
    following: 15,
    created_at: "2021-05-21T19:00:42Z",
    updated_at: "2021-08-02T21:28:10Z"
  }
]